server:
   port: 8080
   servlet:
     context-path: /situ_test1	
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: bean
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1027036251
    url: jdbc:mysql://localhost:3306/st_jsp?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
  mvc:
   view:
    prefix: /test/
    suffix: .jsp